### PR TITLE
Fix typo in CHANGELOG: grpc-web.dart -> grpc_web.dart

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by kevmoo** [comment]
@sigurdm will have to land this – I don't have access

**Comment by chalin** [comment]
Ping @sigurdm & @mit-mit, since you seem to be looking at PRs today :). This is a simple one, already approved by @kevmoo.

**Comment by mit-mit** [comment]
Thanks!

**Comment by kevmoo** [comment]
Would someone w/ the keys land this?

**Pull request merged**
