### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dlotan**
Fix double word

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @Dlotan isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by Dlotan** [comment]
linuxfoundation cla should be done now

**Comment by sigurdm** [comment]
Try to write "I signed it" in a comment as per: https://identity.linuxfoundation.org/projects/cncf (7)

**Comment by Dlotan** [comment]
I signed it

**Comment by sigurdm** [comment]
Not sure why the CLA check still fails.
@mit-mit do you have a clue?

**Comment by mit-mit** [comment]
My best guess would be that the email used to sign the CLA doesn't match the email listed in the git commit?

**Comment by Dlotan** [comment]
I signed it

**Comment by mit-mit** [comment]
Yay, CLA bot is happy!

Thanks for the contribution @Dlotan !

**Pull request merged**
