### PR TITLE
Update dart.yml

### PR DESCRIPTION
**Pull request by mraleph**
grpc master branch name is `master` not `main`.

### CODE REVIEW

**Comment by mit-mit** [comment]
Looks like the failures are in the `example` dir. The Travis CI script has this comment:

```
include:
  # Wish we could exclude `example` in `analysis_options.yaml` but it seems
  # blocked by https://github.com/dart-lang/sdk/issues/26212
  - dart: dev
    dart_task: dartfmt
    script:
    - pub get
    - dartanalyzer lib test
```

That bug is fixed now. Can you try to add this to `analysis_options.yaml`?

```
# Skip analysis of the example dir
analyzer:
  exclude:
  - example/**
```

**Comment by mraleph** [comment]
@mit-mit I am just going to try to replicate what Travis did - analyze each example independently

**Comment by mraleph** [comment]
@mit-mit ha, `dart analyze ` has different CLI interface from `dartanalyzer` - why is that?

`dartanalyzer lib test` works, but `dart analyze lib test` does not.

**Comment by mit-mit** [comment]
For the core code (everything but /example), I think it'll work if you change:
```
      - name: Analyze code (lib and test)
        run: dart analyze lib test
```

to:
```
      - name: Analyze code (lib and test)
        run: dart analyze .
```

**Pull request merged**
