### PR TITLE
fix latency problem when using it as a grpc server or client.

### PR DESCRIPTION
**Pull request by soach**
fix the issue : https://github.com/grpc/grpc-dart/issues/249

### CODE REVIEW

**Comment by sigurdm** [comment]
Thanks for this.
We need you to sign the CLA before landing.

**Comment by ansarizafar** [comment]
Please also fix latency problem in grpc for web.

**Comment by jquenel** [comment]
@soach do you plan on signing the CLA ? If not, can someone else take over the PR ?

**Comment by ansarizafar** [comment]
@sigurdm Any update on when this PR will be merged and released. Will this PR also fix latency problem in grpc for web?

**Comment by sigurdm** [comment]
@ansarizafar 

>Will this PR also fix latency problem in grpc for web?

No, this is only touching grpc on http2.

**Comment by gustav3d** [comment]
Hows it going ?:)

**Comment by sigurdm** [comment]
Closing this for lack of activity.

See instead https://github.com/grpc/grpc-dart/pull/298

**Pull request closed without merging**
