### PR TITLE
Fix issue 669

### PR DESCRIPTION
**Pull request by RubenGarcia**
https://grpc.github.io/grpc/core/md_doc_compression.html indicates that compression flag should not be set if grpc-encoding is identity.

This PR makes grpc-dart set the compression flag properly in this case.

### CODE REVIEW

**Comment by mosuem** [comment]
Thanks a lot for the investigation and the fix! If you could add a changelog entry describing your change (with a link to this PR), as well as adding the information from https://github.com/grpc/grpc-dart/issues/669#issuecomment-2006654280 to this PR description, that would help a lot.

**Comment by RubenGarcia** [comment]
> Thanks a lot for the investigation and the fix! If you could add a changelog entry describing your change (with a link to this PR), as well as adding the information from [#669 (comment)](https://github.com/grpc/grpc-dart/issues/669#issuecomment-2006654280) to this PR description, that would help a lot.

Done and fixed the two issues with the workflow.

**Comment by RubenGarcia** [comment]
I´m getting this error in the other workflow:
```
Validating package:grpc 3.2.4 (dir=/home/runner/work/grpc-dart/grpc-dart):grpc
pubspec:
  - version: 3.2.4
changelog:
* Set compressed flag correctly for grpc-encoding = identity. Fixes [#669](https://github.com/grpc/grpc-dart/issues/669) (https://github.com/grpc/grpc-dart/pull/693)
error: pubspec version (3.2.4) and changelog (null) don't agree
```
Since 3.2.4 has already released, I will change both to 3.2.5.

**Review by mosuem — CHANGES_REQUESTED** [review]
Looking good! If you could add a small test for this to not risk having regressions, we can merge.

**Comment by RubenGarcia** [comment]
> Looking good! If you could add a small test for this to not risk having regressions, we can merge.

Test added.

**Comment by RubenGarcia** [comment]
The error when running dart / test (windows-latest) when running
dart run --enable-vm-service --timeline-streams=Dart test/timeline_test.dart
Could not find a command named "/hostedtoolcache/windows/dart/3.4.0-260.0.d...
seem to be unrelated to my changes.

**Comment by mosuem** [comment]
Right, I will take a look.

**Comment by RubenGarcia** [comment]
Is there anything else needed here?

**Comment by RubenGarcia** [comment]
The failed tests complaining about
dart:js_interop_unsafe
seem to be independent of my changes, although they are a transitive dependency of one of my imports.

**Pull request merged**
