### PR TITLE
Fix interop/bin/server.dart after NNBD migration

### PR DESCRIPTION
**Pull request by cyrax111**

### CODE REVIEW

**Comment by mraleph** [comment]
Thanks for the fix. Could you fix CLA problem so that we could merge?

**Comment by cyrax111** [comment]
I will try ) Do I need to make new commit and pull request after GitHub email changing ?

**Comment by mraleph** [comment]
I think you should be able to force push into the same branch to completely overwrite the history once you fix email on the commit.

**Comment by cyrax111** [comment]
CLA problem was fixed.

**Comment by mraleph** [comment]
Thanks for the fix. Applied.

**Pull request merged**
