### PR TITLE
Fix for duplicate headers

### LINKED ISSUE #380: Breaking change introduced in 2.4.0 grpc-web flutter
Using a commit after bb4eab0f1ff0649760f52e4f911b9e5cfc64df07 generates this error. Seems like something changed in the way the request is made. I'm assuming is the headers.

I tried this against a local envoy proxy and with Google Cloud Run with ESPv2(envoy).

```
errors.dart:167 Uncaught Error: Bad state: Cannot add event after closing
    at Object.throw_ [as throw] (errors.dart:216)
    at _AsyncStreamController.new.addError (stream_controller.dart:633)
    at ClientCall.new.[_onRequestError] (call.dart:370)
    at xhr_transport.dart:71
    at Object._checkAndCall (operations.dart:324)
    at Object.dcall (operations.dart:329)
    at XMLHttpRequest.<anonymous> (html_dart2js.dart:37283)
    at xhr_transport.XhrTransportStream.new.terminate (xhr_transport.dart:148)
    at terminate.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at xhr_transport.XhrTransportStream.new.terminate (xhr_transport.dart:146)
    at ClientCall.new.[_onRequestError] (call.dart:375)
    at xhr_transport.XhrTransportStream.new.[_onHeadersReceived] (xhr_transport.dart:116)
    at xhr_transport.dart:67
    at Object._checkAndCall (operations.dart:324)
    at Object.dcall (operations.dart:329)
    at XMLHttpRequest.<anonymous> (html_dart2js.dart:37283)
```

grpc web init:

```dart
// File created by
// Lung Razvan <long1eu>
// on 16/04/2020

import 'package:firebase/firebase.dart';
import 'package:grpc/grpc_web.dart' as js;
import 'package:grpc/src/client/channel.dart' show ClientChannel;

import 'init.dart' as base;

export 'package:grpc/grpc_web.dart' show CallOptions;
export 'package:grpc/src/client/channel.dart' show ClientChannel;

class InitConfig implements base.InitConfig {
  const InitConfig();

  @override
  ClientChannel get channel {
    if (Config.location == 'cloud') {
      return js.GrpcWebClientChannel.xhr(Uri.parse('https://${Config.endpoint}'));
    } else {
      return js.GrpcWebClientChannel.xhr(Uri.parse('http://localhost:8081'));
    }
  }

  @override
  js.CallOptions get options {
    return js.CallOptions(
      metadata: <String, String>{
        'x-api-key': '<key>',
      },
      providers: <js.MetadataProvider>[
        (Map<String, String> metadata, String url) async {
          if (app().auth().currentUser != null) {
            final String token = await app().auth().currentUser.getIdToken();
            metadata['authorization'] = 'Bearer $token';
          }
        },
      ],
    );
  }
}
```

Let me know if there is anything I can do to help identifying the bug and fixing it. 
Thanks

### PR DESCRIPTION
**Pull request by mraleph**
* Fix #380
* Switch to envoy proxy - grpcwebproxy was too lenient.

### CODE REVIEW

**Comment by mraleph** [comment]
I am gonna TBR this because this essentially a revert and a test only change and I would like to release a new package version today.

**Comment by shaxbee** [comment]
@mraleph Code still outputs duplicate grpc-web headers. Should we recreate #371?

**Comment by mraleph** [comment]
@shaxbee should not be the case. It includes the same type of patch as #371 see https://github.com/grpc/grpc-dart/pull/397/files#diff-b5d4b67a950306222090fd9c916740320086a1241fc0052a8941002423e449cf

**Comment by shaxbee** [comment]
Correct, missed that. Sorry!

**Pull request merged**
