### PR TITLE
Fix broken link to examples

### PR DESCRIPTION
**Pull request by tatsuyafujisaki**
On the following page, clicking "Examples" shows 404 Not Found. This pull request fixes it.
https://pub.dev/documentation/grpc/latest/

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
Thank you!

**Comment by mosuem** [comment]
Link seems to work fine - closing for now.

**Comment by tatsuyafujisaki** [comment]
@mosuem 
No, it doesn't.

Please follow these steps to reproduce the problem ...
1. Open https://pub.dev/documentation/grpc/latest/ in Chrome.
2. Click "Examples" and the 404 Not Found page will appear.

... or watch the screencast below.

https://github.com/user-attachments/assets/f749dc9a-f5fa-4974-a9fa-b6637f375fd6

**Comment by mosuem** [comment]
You are right! Thanks for noticing.

**Comment by mosuem** [comment]
Landed this as part of #732 - thanks @tatsuyafujisaki !

**Pull request closed without merging**
