### PR TITLE
make accessToken in BaseAuthenticator accessible

### PR DESCRIPTION
**Pull request by Ragnaroek**
Use-Case is an own implementation of Token based access control that wants to re-use the BaseAuthenticator functionality.

### CODE REVIEW

**Comment by Ragnaroek** [comment]
@googlebot I signed it!

**Comment by Ragnaroek** [comment]
@googlebot I signed it!

**Comment by sigurdm** [comment]
I am not against this.

I don't like the design of the class hierarchy that much, thinking that the BaseAuthenticator should probably not have been exposed like that, but that's what we have for now.

@jonasfj what do you think?

**Comment by jonasfj** [comment]
I would either:

-----
A) Create a new base class for `BaseAuthenticator` called `Authenticator` and replace uses of `BaseAuthenticator` throught-out the code-base... (also fix the documentation todos).

```dart
// TODO: Document this
abstract class Authenticator {
  // TODO: Document this
  Future<void> authenticate(Map<String, String> metadata, String uri);
  // TODO: Document this
  CallOptions get toCallOptions => CallOptions(providers: [authenticate]);
}

@deprecated
abstract class BaseAuthenticator extends Authenticator {
  // remains as is...
}
```
Then follow up with something like:
```dart
// TODO: Document this
abstract class Authenticator {
  // TODO: Document this
  Future<void> authenticate(Map<String, String> metadata, String uri);
  // TODO: Document this
  CallOptions get toCallOptions => CallOptions(providers: [authenticate]);

  /// Create an [Authenticator] given a method [getAccessToken] which
  /// can obtain an [auth.AccessToken] for a given URI.
  static Authenticator create(Future<auth.AccessToken> Function(String uri) getAccessToken)
    => _Authenticator(getAccessToken);
}

@deprecated
abstract class BaseAuthenticator extends Authenticator {
  // remains as is...
}

class _Authenticator extends BaseAuthenticator {
  final Future<auth.AccessToken> Function(String uri) _getAccessToken;

  _Authenticator(this._getAccessToken);

  @override
  Future<void> obtainAccessCredentials(String uri) async
    => _accessToken = await _getAccessToken(uri);
}
```


------------------
B) Create a static `BaseAuthenticator.create` method that accepts a function to do this, something like this:

```dart
abstract class BaseAuthenticator {
  // remains as is...

  /// Create a [BaseAuthenticator] given a method [getAccessToken] which
  /// can obtain an [auth.AccessToken] for a given URI.
  static BaseAuthenticator create(Future<auth.AccessToken> Function(String uri) getAccessToken)
    => _Authenticator(getAccessToken);
}

class _Authenticator extends BaseAuthenticator {
  final Future<auth.AccessToken> Function(String uri) _getAccessToken;

  _Authenticator(this._getAccessToken);

  @override
  Future<void> obtainAccessCredentials(String uri) async
    => _accessToken = await _getAccessToken(uri);
}
```

It's less clean-up than solution (A), but also a lot easier to implement.

Note. I would strongly advice a method like `BaseAuthenticator.create` be documented with an inline-example in addition to some explanation.


-----
Warnings, this just quick code snippets, I haven't tested or fully thought this through.

**Comment by mit-mit** [comment]
Closing due to unresolved design issues.

**Pull request closed without merging**
