### PR TITLE
fix sending header to an already closed stream

### LINKED ISSUE #111: Bad state: Cannot add event after closing
I got this error when i terminate a client and the client is listening to a Stream.

here is the proto:
```proto
syntax = "proto3";

package bug;

import "common.proto";

message Hello {
    string hello = 1;
}

service BugService {
    rpc infiniteStream (common.Empty) returns (stream Hello) {
    }
}
```

here is the service code :
```dart
class BugService extends BugServiceBase {
  final infiniteStreamController = StreamController.broadcast<Hello>();
  int count = 0;

  BugService() {
    Timer.periodic(Duration(seconds: 1), (_) {
      count++;
      infiniteStreamController.add(Hello()..hello = 'Hello $count');
    });
  }

  @override
  Stream<Hello> infiniteStream(ServiceCall call, Empty request) async* {
    await for (final hello in infiniteStreamController.stream) {
      yield hello;
    }
  }
}
```

and here is the client
```dart
Future<void> main() async {
  final channel = ClientChannel(
    'localhost',
    port: 8080,
    options: const ChannelOptions(
      credentials: const ChannelCredentials.insecure(),
    ),
  );
  final client = BugServiceClient(channel);
  final completer = Completer<void>();
  final subscription = client.infiniteStream(Empty()).listen(print);
  ProcessSignal.sigint.watch().listen((_) async {
    await subscription.cancel();
    print('quit gracefully');
    await channel.terminate();
    completer.complete();
  });
  await completer.future;
  exit(0);
}
```

and here is the stacktrace when the server crash
```
Unhandled exception:
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:584:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#2      TransportStream.sendHeaders (package:http2/transport.dart:241:10)
#3      ServerHandler.sendTrailers (package:grpc/src/server/handler.dart:301:13)
#4      ServerHandler._sendError (package:grpc/src/server/handler.dart:350:5)
#5      ServerHandler._onResponse (package:grpc/src/server/handler.dart:239:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#14     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Question:
How to stop sending value to the stream when the client quit ?

### PR DESCRIPTION
**Pull request by Kleak**
This fix #111

### CODE REVIEW

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* User @Kleak isn't covered by a CLA. They will need to complete the form at https://identity.linuxfoundation.org/projects/cncf

_Regards,
CLA GitHub bot_

**Comment by Kleak** [comment]
signed cla/linuxfoundation

**Comment by kevmoo** [comment]
CC @sortie @mit-mit

**Comment by Kleak** [comment]
So we need  to listen `_stream.outgoingMessages` cancelation and close the response subscription.

**Comment by Kleak** [comment]
The error happen because `_stream.outgoingMessages` is already closed.
and nothing notify the service that we need to close the controller.

like in this example :
```dart
class BugService extends BugServiceBase {
  final infiniteStreamController = StreamController.broadcast<Hello>();
  final _subscription = <int, StreamSubscription<Hello>>{};

  int count = 0;
  int clientId = 0;

  BugService() {
    Timer.periodic(Duration(seconds: 1), (_) {
      count++;
      infiniteStreamController.add(Hello()..hello = 'Hello $count');
    });
  }

  @override
  Stream<Hello> infiniteStream(ServiceCall call, Empty request) {
    final controller = StreamController.broadcast<Hello>();
    final _clientId = clientId++;
    _subscription[_clientId] =
        infiniteStreamController.stream.listen((hello) async {
      print('');
      print('isClose ${controller.isClosed}');
      print('hasListener ${controller.hasListener}');
      print('isPaused ${controller.isPaused}');
      print('isCanceled ${call.isCanceled}');
      print('');
      if (!call.isCanceled && !controller.isClosed && controller.hasListener) {
        controller.add(hello);
      }
      if (!controller.hasListener) {
        _subscription[_clientId].cancel();
        controller.close();
      }
    });

    return controller.stream;
  }
}
```

with my workaround the hasListener field of the controller is true when the client is connected and false when we kill the client. So i can close the controller.

**Comment by sigurdm** [comment]
Sorry for letting you wait. I really hope to find time for this monday

**Comment by sigurdm** [comment]
So it seems changing ServerHandler.handle to the following (listening to done of outgoingMessages) solves the problem:
```
  void handle() {
    _stream.onTerminated = (int errorCode) {
      _isCanceled = true;
      _timeoutTimer?.cancel();
      _cancelResponseSubscription();
    };

    _stream.outgoingMessages.done.then((_) {
      _isCanceled = true;
      _timeoutTimer?.cancel();
      _cancelResponseSubscription();
    });

    _incomingSubscription = _stream.incomingMessages
        .transform(new GrpcHttpDecoder())
        .transform(grpcDecompressor())
        .listen(_onDataIdle,
            onError: _onError, onDone: _onDoneError, cancelOnError: true);
  }
```
I am still struggling with writing a test case that exhibits the problem to prevent further regressions. Will continue investigating.

**Comment by mit-mit** [comment]
@sigurdm any news on this one?

**Pull request closed without merging**
