### PR TITLE
Close transport connection properly

### PR DESCRIPTION
**Pull request by hubaxis**
Sometimes connection never finished. Force terminate it after timeout

### CODE REVIEW

**Comment by hubaxis** [comment]
Any progress here?

**Comment by long1eu** [comment]
I someone watching this PR's?

**Comment by mit-mit** [comment]
This looks like a good, small change, cc @mraleph

**Review by mraleph — CHANGES_REQUESTED** [review]
- Please describe what we want to achieve by terminating connection forcefully, e.g. we want to prevent resource leak when connection is just hanging out there.
- If possible provide test case, if not at least describe why you want this change to be made, how did you discover that this happens and is an issue.

**Comment by mraleph** [comment]
Closing assuming stale.

**Pull request closed without merging**
