### PR TITLE
Prevent an exception to be thrown when a web connection stream is closed

### PR DESCRIPTION
**Pull request by Herrera93**
- Related #206

### CODE REVIEW

**Comment by mraleph** [comment]
Hi @Herrera93,

Thank you for the contribution. 

Please rebase your branch - that should unblock testing.  

We would also need tests for this specific test to prevent regressions in the future.

**Comment by mraleph** [comment]
Thank you for adding a test.

I have looked at things more closely and I can see that the root cause of the issue is that we are checking whether `_incommingMessages` are closed, but we should be rather checking that `_incommingProcessor` is closed (when processor is closed it propagates closure to messages stream - but this happens asynchronously so it might race with other events, which causes this bug).

I think the proper fix is like this (no need to introduce `_terminated`):

```diff
diff --git a/lib/src/client/transport/xhr_transport.dart b/lib/src/client/transport/xhr_transport.dart
index 89259c5..9244491 100644
--- a/lib/src/client/transport/xhr_transport.dart
+++ b/lib/src/client/transport/xhr_transport.dart
@@ -44,7 +44,6 @@ class XhrTransportStream implements GrpcTransportStream {
   final StreamController<ByteBuffer> _incomingProcessor = StreamController();
   final StreamController<GrpcMessage> _incomingMessages = StreamController();
   final StreamController<List<int>> _outgoingMessages = StreamController();
-  bool _terminated = false;
 
   @override
   Stream<GrpcMessage> get incomingMessages => _incomingMessages.stream;
@@ -60,7 +59,7 @@ class XhrTransportStream implements GrpcTransportStream {
         .listen((data) => _request.send(data), cancelOnError: true);
 
     _request.onReadyStateChange.listen((data) {
-      if (_incomingMessages.isClosed || _terminated) {
+      if (_incomingProcessor.isClosed) {
         return;
       }
       switch (_request.readyState) {
@@ -81,7 +80,7 @@ class XhrTransportStream implements GrpcTransportStream {
     });
 
     _request.onError.listen((ProgressEvent event) {
-      if (_incomingMessages.isClosed) {
+      if (_incomingProcessor.isClosed) {
         return;
       }
       _onError(GrpcError.unavailable('XhrConnection connection-error'),
@@ -90,7 +89,7 @@ class XhrTransportStream implements GrpcTransportStream {
     });
 
     _request.onProgress.listen((_) {
-      if (_incomingMessages.isClosed) {
+      if (_incomingProcessor.isClosed) {
         return;
       }
       // Use response over responseText as most browsers don't support
@@ -151,7 +150,6 @@ class XhrTransportStream implements GrpcTransportStream {
 
   @override
   Future<void> terminate() async {
-    _terminated = true;
     _close();
     _request.abort();
   }
```

Could you apply this patch on top of your branch (normally I would be able to just commit a patch myself into the PR - but you created PR from your master branch which prevents me from doing this, so I have to ask you do it).

After that I can land the PR.

**Comment by long1eu** [comment]
can we have this published?

**Comment by mraleph** [comment]
Published 2.9.0

**Pull request merged**
