### PR TITLE
Ensure CallOptions merge preserves Web specific options

### PR DESCRIPTION
**Pull request by zbigniew-mandziejewicz-3r**
When WebCallOptions are merged with CallOptions data is lost, this PR preserves the original WebCallOptions flags and returns correct type.

### CODE REVIEW

**Comment by shaxbee** [comment]
@mraleph We should land this to make interceptors that modify `callOptions` work with grpc-web clients.

**Comment by mraleph** [comment]
Please add a test to make sure we don't break it again. I would be happy to merge afterwards. 

(We are looking at ways to mitigate Travis slowness in the meantime)

**Comment by shaxbee** [comment]
> Please add a test to make sure we don't break it again. I would be happy to merge afterwards.

Done.

**Comment by shaxbee** [comment]
@mraleph Please trigger rebuild if chrome issue are resolved.

**Pull request merged**
