### PR TITLE
Implement client-side interceptor

### PR DESCRIPTION
**Pull request by lqs**
This implements client-side interceptor (also mentioned in #121), which is helpful for tracking request duration or adding global error handler.

Usage example:
```
ClientInterceptor _interceptor = (method, requests, options, invoker) {
  final startTime = DateTime.now();
  print("start call ${method.path}");

  final call = invoker(method, requests.map((request) {
    print("request: ${request.runtimeType}($request)");
    return request;
  }), options);

  call.headers.then((headers) {
    print("headers: $headers");
  });
  call.trailers.then((trailers) {
    print("trailers: $trailers");
    final endTime = DateTime.now();
    print(endTime.difference(startTime));
  });

  call.response.listen((response) {
    print("response value: ${response.runtimeType}($response)");
  });

  return call;
};

var channel = ClientChannel("host-of-grpc-service", interceptor: _interceptor);
```

---

Admin-comment: Fixes https://github.com/grpc/grpc-dart/issues/121

### CODE REVIEW

**Comment by cosmotek** [comment]
does this provide access to the request metadata? I think something that needs to be possible here is changing metadata (auth) on specific error and re-execing the call.

**Comment by cosmotek** [comment]
I've been playing with implementing the same thing for the last hour or so.... Not sure if I know what I am doing, but I realize that these changes require changes to the protoc-gen-dart generator project as well.

**Comment by lqs** [comment]
@cosmotek Yes, the request metadata can be accessed in `options.metadata`

**Comment by phamnhuvu-dev** [comment]
This code doesn't support `async function`. Sometimes you will need call `async function` to get data for `metadata`
I wrote an interceptor for `async function` to update `options.metadata` but now I am busy with the deadline. Sorry 
See you later soon.

**Comment by upday7** [comment]
this this pr being reviewed? .. hope this will be in next release ..

**Comment by gustav3d** [comment]
Hows review going ?

**Comment by cq-z** [comment]
@lqs support web code
web_channel.dart:
``GrpcWebClientChannel.xhr(this.uri,interceptor)` : super(interceptor: interceptor);
``

**Comment by nateshmbhat** [comment]
any progress on this ?

**Comment by nateshmbhat** [comment]
@lqs how do we modify the response here ?

Only the request object passes through the interceptor. So modification to the request is possible.

How about modification to the response ? here we are only listening to the response. any idea how to add that feature to the interceptor. ?

**Comment by Arpit1496** [comment]
Why this is not merged yet ?

**Comment by Arpit1496** [comment]
Why this is not merged yet ?

**Comment by mraleph** [comment]
We are reviewing a more feature complete version of this functionality here https://github.com/grpc/grpc-dart/pull/338. I am going to close this PR in favor of #338.

**Pull request closed without merging**
