### PR TITLE
generative language

### PR DESCRIPTION
**Pull request by kevmoo**
- Regenerate code with latest formatter
- Generate language model

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by kevmoo** [comment]
@domesticmouse – not going to land this...at least not right away. Just wanted to share the generated output if someone wants to run w/ it

**Comment by domesticmouse** [comment]
> @domesticmouse – not going to land this...at least not right away. Just wanted to share the generated output if someone wants to run w/ it

What are the downsides of landing this as is? It'll be easier for people to build atop this PR rather than having to figure it all out for themselves.

**Comment by kevmoo** [comment]
> What are the downsides of landing this as is? It'll be easier for people to build atop this PR rather than having to figure it all out for themselves.

It's completely unrelated to the example here. We should add a seperate example just for this.

Trying to bootstrap someone.

**Comment by dishankjindal1** [comment]
Why this PR is not merged? why the hold up?

**Comment by kevmoo** [comment]
@dishankjindal1 – it's JUST an example. I should delete it honestly. We need to find a better spot to host it!

**Comment by kevmoo** [comment]
Closing this out. AI Platform was adding in v11.4 https://pub.dev/packages/googleapis

**Pull request closed without merging**
